# Generated by Django 4.0.2 on 2022-02-23 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archs.category'),
        ),
    ]
